/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "Counter_1.h"
#include "isr_contador.h"
#include "Clock_1.h"
#include "Seg_aliases.h"
#include "Seg.h"
#include "Com_aliases.h"
#include "Com.h"
#include "LED_Driver.h"
#include "LCD.h"
#include "data.h"
#include "tilt_aliases.h"
#include "tilt.h"
#include "PWM.h"
#include "Clock_2.h"
#include "Clock_3.h"
#include "motor_aliases.h"
#include "motor.h"
#include "aum.h"
#include "dism.h"
#include "bt_aum_aliases.h"
#include "bt_aum.h"
#include "bt_dis_aliases.h"
#include "bt_dis.h"
#include "aviso_aliases.h"
#include "aviso.h"
#include "ADC.h"
#include "tem_aliases.h"
#include "tem.h"
#include "Opamp.h"
#include "UART_1_IntClock.h"
#include "LED_Driver_ClkInternal.h"
#include "LED_Driver_Seg_Driver_L.h"
#include "LED_Driver_Com_Driver.h"
#include "LED_Driver_DMA_Com_dma.h"
#include "LED_Driver_DMA_Seg_dma.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

